#include "services/pools.hpp"

#include <cstdio>
#include <fstream>
#include <sstream>

#ifndef _WIN32
#include <grp.h>
#include <pwd.h>
#include <sys/stat.h>
#include <unistd.h>
#endif

namespace agensio {

namespace fs = std::filesystem;

namespace {

constexpr const char* kHeader = "; generated by agensio";

std::string join(const std::vector<std::string>& parts, char sep) {
    std::string out;
    for (const auto& p : parts) {
        if (!out.empty()) out += sep;
        out += p;
    }
    return out;
}

// php.ini shorthand for the body limit: whole megabytes when it divides, else bytes.
std::string ini_size(std::size_t bytes) {
    const std::size_t mb = 1024 * 1024;
    if (bytes % mb == 0) return std::to_string(bytes / mb) + "M";
    return std::to_string(bytes);
}

}  // namespace

std::string render_pool(const Config& cfg, const SiteConfig& site, const std::string& agensio_group) {
    const PhpPool& p = site.pool;
    std::ostringstream o;
    o << kHeader << " from " << cfg.config_path.string() << " for user " << site.user
      << "; do not edit, rerun `agensio pools`\n";
    o << "[" << p.name << "]\n";
    o << "user = " << site.user << "\n";
    o << "group = " << (site.group.empty() ? site.user : site.group) << "\n";
    o << "listen = " << p.socket << "\n";
    o << "listen.owner = " << site.user << "\n";
    o << "listen.group = " << agensio_group << "\n";
    o << "listen.mode = 0660\n";
    o << "pm = " << p.pm << "\n";
    o << "pm.max_children = " << p.children << "\n";
    if (p.pm == "dynamic") {
        // Half the children on standby, one idle at least: php-fpm insists on these keys.
        const unsigned start = std::max(1u, p.children / 2);
        o << "pm.start_servers = " << start << "\npm.min_spare_servers = 1\npm.max_spare_servers = " << start
          << "\n";
    }
    if (p.max_requests) o << "pm.max_requests = " << p.max_requests << "\n";
    o << "catch_workers_output = yes\n";
    o << "clear_env = yes\n";
    o << "env[PATH] = /usr/local/bin:/usr/bin:/bin\n";
    o << "php_admin_value[open_basedir] = " << join(p.open_basedir, ':') << "\n";
    o << "php_admin_value[upload_tmp_dir] = " << p.state_dir << "/tmp\n";
    o << "php_admin_value[sys_temp_dir] = " << p.state_dir << "/tmp\n";
    o << "php_admin_value[session.save_path] = " << p.state_dir << "/sessions\n";
    o << "php_admin_value[memory_limit] = " << p.memory_limit << "\n";
    o << "php_admin_value[max_execution_time] = " << p.max_execution_time << "\n";
    o << "php_admin_value[upload_max_filesize] = " << ini_size(cfg.max_body_size) << "\n";
    o << "php_admin_value[post_max_size] = " << ini_size(cfg.max_body_size) << "\n";
    o << "php_admin_flag[expose_php] = off\n";
    for (const auto& [k, v] : p.extra) o << "php_admin_value[" << k << "] = " << v << "\n";
    return o.str();
}

std::vector<GeneratedPool> generated_pools(const Config& cfg, const std::string& agensio_group) {
    std::vector<GeneratedPool> out;
    for (const auto& site : cfg.sites) {
        if (!site.pool.generated) continue;
        bool seen = false;
        for (const auto& g : out) seen = seen || g.user == site.user;
        if (seen) continue;  // the sites of a user agree (checked at load); the first renders
        out.push_back({site.pool.name, site.user, site.group.empty() ? site.user : site.group, site.pool.state_dir,
                       render_pool(cfg, site, agensio_group)});
    }
    return out;
}

std::string current_group_name() {
#ifndef _WIN32
    if (const struct group* g = ::getgrgid(::getegid())) return g->gr_name;
#endif
    return {};
}

fs::path pools_dir(const Config& cfg, const std::string& version) {
    if (!cfg.pools_dir.empty()) return cfg.pools_dir;
    // Debian/Ubuntu: /etc/php/<version>/fpm/pool.d; brew: <prefix>/etc/php/<version>/php-fpm.d;
    // RHEL/Fedora: /etc/php-fpm.d; Alpine: /etc/php<NN>/php-fpm.d. Newest version wins.
    std::error_code ec;
    for (const char* prefix : {"/etc/php", "/opt/homebrew/etc/php", "/usr/local/etc/php"}) {
        const fs::path base(prefix);
        if (!fs::is_directory(base, ec)) continue;
        fs::path best;
        for (const auto& entry : fs::directory_iterator(base, ec)) {
            const std::string v = entry.path().filename().string();
            if (!version.empty() && v != version) continue;
            if (!fs::is_directory(entry.path() / "fpm" / "pool.d", ec) &&
                !fs::is_directory(entry.path() / "php-fpm.d", ec))
                continue;
            if (best.empty() || v > best.filename().string()) best = entry.path();
        }
        if (best.empty()) continue;
        return fs::is_directory(best / "fpm" / "pool.d", ec) ? best / "fpm" / "pool.d" : best / "php-fpm.d";
    }
    if (fs::is_directory("/etc/php-fpm.d", ec)) return "/etc/php-fpm.d";
    for (const auto& entry : fs::directory_iterator("/etc", ec)) {
        const std::string n = entry.path().filename().string();
        if (n.starts_with("php") && fs::is_directory(entry.path() / "php-fpm.d", ec)) return entry.path() / "php-fpm.d";
    }
    return {};
}

HostFacts system_facts() {
    HostFacts f;
#ifndef _WIN32
    f.stat = [](const std::string& path, FileFacts& out) {
        struct stat st {};
        if (::stat(path.c_str(), &st) != 0) return false;
        out.is_dir = S_ISDIR(st.st_mode);
        out.uid = st.st_uid;
        out.gid = st.st_gid;
        out.mode = st.st_mode & 07777;
        return true;
    };
    f.user = [](const std::string& name, unsigned& uid, unsigned& gid) {
        const struct passwd* pw = ::getpwnam(name.c_str());
        if (!pw) return false;
        uid = pw->pw_uid;
        gid = pw->pw_gid;
        return true;
    };
    f.group = [](const std::string& name, unsigned& gid) {
        const struct group* gr = ::getgrnam(name.c_str());
        if (!gr) return false;
        gid = gr->gr_gid;
        return true;
    };
    f.group_name = [](unsigned gid) -> std::string {
        const struct group* gr = ::getgrgid(gid);
        return gr ? gr->gr_name : std::string();
    };
#else
    f.stat = [](const std::string&, FileFacts&) { return false; };
    f.user = [](const std::string&, unsigned&, unsigned&) { return false; };
    f.group = [](const std::string&, unsigned&) { return false; };
    f.group_name = [](unsigned) { return std::string(); };
#endif
    return f;
}

ServerAccount server_account(const Config& cfg, const HostFacts& facts) {
    ServerAccount a;
    a.user = cfg.user;
    unsigned primary = 0;
    bool user_ok = true;
    if (!cfg.user.empty()) {
        user_ok = facts.user(cfg.user, a.uid, primary);
    } else {
#ifndef _WIN32
        a.uid = ::geteuid();
        primary = ::getegid();
#endif
    }
    if (!cfg.group.empty()) {
        a.group = cfg.group;
        a.known = facts.group(cfg.group, a.gid) && user_ok;
        return a;
    }
    if (!user_ok) return a;  // the caller reports the missing account
    a.gid = primary;
    a.group = facts.group_name ? facts.group_name(primary) : std::string();
    a.known = !a.group.empty();
    return a;
}

namespace {

std::string octal(unsigned mode) {
    char buf[8];
    std::snprintf(buf, sizeof buf, "%04o", mode);
    return buf;
}

// One site's accounts and the paths its rules apply to.
struct SiteFacts {
    const SiteConfig* site = nullptr;
    std::string name;
    unsigned uid = 0, gid = 0;
};

}  // namespace

std::vector<std::string> check_hosting(const Config& cfg, const HostFacts& facts) {
    std::vector<std::string> errors;
    std::vector<SiteFacts> sites;
    bool any_user = false;
    for (const auto& site : cfg.sites) any_user = any_user || !site.user.empty();
    if (!any_user) return errors;
    const ServerAccount server = server_account(cfg, facts);
    const unsigned agensio_gid = server.gid;
    const bool have_agensio_gid = server.known;
    const std::string agensio_group = server.group.empty() ? std::string("?") : server.group;
    if (!have_agensio_gid) {
        if (!cfg.group.empty()) errors.push_back("server.group: group '" + cfg.group + "' does not exist (the group the server runs as)");
        else if (!cfg.user.empty()) errors.push_back("server.user: user '" + cfg.user + "' does not exist");
        else errors.push_back("server.group: cannot resolve the group the server runs as (set server.group)");
    }
    // The server reads static files and stats scripts as server.user: a root it cannot
    // enter serves nothing. Root sees everything, so the rule needs a configured user.
    const bool server_reads = !cfg.user.empty() && server.known && server.uid != 0;
    auto server_can_read = [&](const FileFacts& f) {
        if (f.uid == server.uid) return (f.mode & 0500) == 0500;
        if (have_agensio_gid && f.gid == agensio_gid) return (f.mode & 0050) == 0050;
        return (f.mode & 0005) == 0005;
    };

    // Rule 1: accounts exist.
    for (const auto& site : cfg.sites) {
        if (site.user.empty()) continue;
        SiteFacts sf;
        sf.site = &site;
        sf.name = "site " + site.server_names.front();
        unsigned primary = 0;
        if (!facts.user(site.user, sf.uid, primary)) {
            errors.push_back(sf.name + ": user '" + site.user + "' does not exist");
            continue;
        }
        sf.gid = primary;
        if (!site.group.empty() && !facts.group(site.group, sf.gid)) {
            errors.push_back(sf.name + ": group '" + site.group + "' does not exist");
            continue;
        }
        sites.push_back(sf);
    }

    auto describe = [&](const FileFacts& f) { return "owned by uid " + std::to_string(f.uid) + " gid " +
                                                     std::to_string(f.gid) + " mode " + octal(f.mode); };
    // Rule 2: a directory the user's PHP runs from is the user's (or root's) and nobody else
    // can write into it. Rule 3: a secret is readable by the user's own group at most.
    auto check_root = [&](const SiteFacts& sf, const std::string& path, const char* what, bool server_must_read) {
        FileFacts f;
        if (!facts.stat(path, f)) return;  // state directories appear with `agensio pools`
        if (f.uid != sf.uid && f.uid != 0)
            errors.push_back(sf.name + ": " + what + " " + path + " is " + describe(f) + "; expected owner " +
                             sf.site->user + " (uid " + std::to_string(sf.uid) + ") or root");
        if ((f.mode & 0002) || ((f.mode & 0020) && f.gid != sf.gid))
            errors.push_back(sf.name + ": " + what + " " + path + " is writable by other users (" + describe(f) +
                             "); remove the write bit for others" +
                             ((f.mode & 0020) && f.gid != sf.gid ? " and for group " + std::to_string(f.gid) : ""));
        // Rule 2b: the server's account must be able to enter what it serves from (static
        // files, script stat); the user's private tmp/ and sessions/ are PHP's alone.
        if (server_must_read && server_reads && f.is_dir && !server_can_read(f))
            errors.push_back(sf.name + ": " + what + " " + path + " is " + describe(f) + "; the server (" +
                             (server.user.empty() ? "uid " + std::to_string(server.uid) : server.user) + ", group " +
                             agensio_group + ") cannot read it. Give it the server's group: chown " + sf.site->user + ":" +
                             agensio_group + " " + path + " && chmod 2750 " + path);
    };
    auto check_secret = [&](const SiteFacts& sf, const std::string& path) {
        FileFacts f;
        if (!facts.stat(path, f)) return;
        if ((f.mode & 0004) || ((f.mode & 0040) && f.gid != sf.gid))
            errors.push_back(sf.name + ": " + path + " is readable by other users (" + describe(f) +
                             "); make it 0600, or 0640 with the site's own group (" +
                             (sf.site->group.empty() ? sf.site->user : sf.site->group) + "), never the server's");
    };
    for (const auto& sf : sites) {
        const SiteConfig& site = *sf.site;
        check_root(sf, site.root, "root", true);
        for (const auto& dir : site.pool.open_basedir)
            if (dir != site.root) check_root(sf, dir, "open_basedir entry", site.root.starts_with(dir + "/"));
        const std::string project = site.pool.open_basedir.empty() ? site.root : site.pool.open_basedir.front();
        check_secret(sf, site.root + "/.git");
        if (site.app == "laravel") {
            for (const char* rel : {"/.env", "/config", "/storage", "/.git"}) check_secret(sf, project + rel);
        } else if (site.app == "wordpress") {
            check_secret(sf, site.root + "/wp-config.php");
        } else {
            check_secret(sf, site.root + "/.env");
        }
        // Rule 4: the pool socket is the user's, and only agensio's group may connect.
        if (site.php.configured && site.php.address.unix) {
            FileFacts f;
            const std::string& sock = site.php.address.path;
            if (facts.stat(sock, f)) {
                if (f.uid != sf.uid)
                    errors.push_back(sf.name + ": socket " + sock + " is " + describe(f) + "; expected owner " +
                                     site.user);
                if (have_agensio_gid && f.gid != agensio_gid)
                    errors.push_back(sf.name + ": socket " + sock + " has gid " + std::to_string(f.gid) +
                                     "; expected group " + agensio_group + " (gid " + std::to_string(agensio_gid) +
                                     "), the server's group: the server connects through the group bit and nobody "
                                     "else can (listen.group in the pool file, as `agensio pools` writes it)");
                if (f.mode & 0007)
                    errors.push_back(sf.name + ": socket " + sock + " is mode " + octal(f.mode) +
                                     "; any user could connect, make it 0660");
            }
            FileFacts d;
            const std::string dir = fs::path(sock).parent_path().string();
            if (facts.stat(dir, d) && (d.mode & 0002) && !(d.mode & 01000))
                errors.push_back(sf.name + ": socket directory " + dir + " is world-writable (" + describe(d) +
                                 "); another user could replace the socket");
        }
        // Rule 6: the access log is the site's to read, nobody else's.
        if (!site.access_log.empty()) {
            FileFacts f;
            if (facts.stat(site.access_log, f) &&
                ((f.mode & 0004) || ((f.mode & 0040) && f.gid != sf.gid && (!have_agensio_gid || f.gid != agensio_gid))))
                errors.push_back(sf.name + ": access log " + site.access_log + " is readable by other users (" +
                                 describe(f) + ")");
            FileFacts d;
            const std::string dir = fs::path(site.access_log).parent_path().string();
            if (facts.stat(dir, d) && ((d.mode & 0002) || ((d.mode & 0020) && d.uid != 0 && d.gid != agensio_gid)))
                errors.push_back(sf.name + ": log directory " + dir + " is writable by other users (" + describe(d) +
                                 "); a site user could plant a symlink there");
        }
    }
    // Rule 5: nothing is shared between different users.
    for (std::size_t i = 0; i < sites.size(); ++i)
        for (std::size_t j = i + 1; j < sites.size(); ++j) {
            const SiteConfig& a = *sites[i].site;
            const SiteConfig& b = *sites[j].site;
            if (a.user == b.user) continue;
            const std::string pair = sites[i].name + " (" + a.user + ") and " + b.server_names.front() + " (" + b.user + ")";
            if (a.root == b.root || a.root.starts_with(b.root + "/") || b.root.starts_with(a.root + "/"))
                errors.push_back(pair + " have different users but nested or equal roots " + a.root + " and " + b.root);
            if (!a.access_log.empty() && a.access_log == b.access_log)
                errors.push_back(pair + " have different users but the same access log " + a.access_log);
            if (a.pool.generated && b.pool.generated && a.pool.state_dir == b.pool.state_dir)
                errors.push_back(pair + " have different users but the same state directory " + a.pool.state_dir);
        }
    return errors;
}

int write_pools(const Config& cfg, const fs::path& out_dir, bool dry_run, std::ostream& out) {
#ifdef _WIN32
    (void)cfg;
    (void)out_dir;
    (void)dry_run;
    out << "error: generated php-fpm pools are not supported on Windows\n";
    return 1;
#else
    const std::string agensio_group = server_account(cfg, system_facts()).group;
    if (agensio_group.empty()) {
        out << "error: cannot determine the group the server runs as; set server.user or server.group\n";
        return 1;
    }
    std::error_code ec;
    if (!fs::is_directory(out_dir, ec)) {
        out << "error: pool directory " << out_dir.string() << " does not exist\n";
        return 1;
    }
    const auto pools = generated_pools(cfg, agensio_group);
    bool changed = false;
    const char* verb = dry_run ? "would write" : "wrote";

    for (const auto& p : pools) {
        // State directories: 0700 and owned by the user; chown needs root, so without it
        // the directories stay ours and one warning per user says what to fix.
        const struct passwd* pw = ::getpwnam(p.user.c_str());
        const struct group* gr = ::getgrnam(p.group.c_str());
        bool own_warned = false;
        for (const char* sub : {"", "/tmp", "/sessions"}) {
            const fs::path d = p.state_dir + sub;
            if (fs::is_directory(d, ec)) continue;
            if (dry_run) {
                out << "would create " << d.string() << "\n";
                continue;
            }
            if (!fs::create_directories(d, ec) && ec) {
                out << "error: cannot create " << d.string() << ": " << ec.message() << "\n";
                return 1;
            }
            ::chmod(d.c_str(), 0700);
            const bool owned = pw && gr && ::chown(d.c_str(), pw->pw_uid, gr->gr_gid) == 0;
            if (!owned && !own_warned) {
                own_warned = true;
                if (!pw || !gr) out << "warning: user " << p.user << " or group " << p.group << " does not exist; ";
                else out << "warning: not root, cannot chown; ";
                out << p.state_dir << " stays owned by us and PHP cannot write there until it is "
                    << p.user << ":" << p.group << "\n";
            }
            out << "created " << d.string() << "\n";
        }
        const fs::path file = out_dir / (p.name + ".conf");
        std::string current;
        if (std::ifstream in(file); in) current.assign(std::istreambuf_iterator<char>(in), {});
        if (current == p.text) continue;
        if (!current.empty() && !current.starts_with(kHeader)) {
            out << "error: " << file.string() << " exists and was not generated by agensio; remove it or rename the user\n";
            return 1;
        }
        changed = true;
        out << verb << " " << file.string() << "\n";
        if (dry_run) continue;
        const fs::path tmp = file.string() + ".tmp";
        {
            std::ofstream f(tmp, std::ios::trunc);
            f << p.text;
            if (!f) {
                out << "error: cannot write " << tmp.string() << "\n";
                return 1;
            }
        }
        ::chmod(tmp.c_str(), 0644);
        fs::rename(tmp, file, ec);
        if (ec) {
            out << "error: cannot replace " << file.string() << ": " << ec.message() << "\n";
            return 1;
        }
    }

    // Files we generated for users that are no longer configured.
    for (const auto& entry : fs::directory_iterator(out_dir, ec)) {
        const std::string name = entry.path().filename().string();
        if (!name.starts_with("agensio-") || !name.ends_with(".conf")) continue;
        bool wanted = false;
        for (const auto& p : pools) wanted = wanted || name == p.name + ".conf";
        if (wanted) continue;
        std::string first;
        std::ifstream in(entry.path());
        std::getline(in, first);
        if (!first.starts_with(kHeader)) continue;
        changed = true;
        out << (dry_run ? "would remove " : "removed ") << entry.path().string() << "\n";
        if (!dry_run) fs::remove(entry.path(), ec);
    }
    if (!changed) out << "pools up to date (" << pools.size() << ")\n";
    else if (!dry_run) out << "reload php-fpm to apply\n";
    return changed ? 3 : 0;
#endif
}

}  // namespace agensio
