#include "services/pools.hpp"

#include <fstream>
#include <map>
#include <sstream>

#ifndef _WIN32
#include <grp.h>
#include <pwd.h>
#include <sys/stat.h>
#include <unistd.h>
#endif

namespace agensio {

namespace fs = std::filesystem;

namespace {

constexpr const char* kHeader = "; generated by agensio";

std::string join(const std::vector<std::string>& parts, char sep) {
    std::string out;
    for (const auto& p : parts) {
        if (!out.empty()) out += sep;
        out += p;
    }
    return out;
}

// php.ini shorthand for the body limit: whole megabytes when it divides, else bytes.
std::string ini_size(std::size_t bytes) {
    const std::size_t mb = 1024 * 1024;
    if (bytes % mb == 0) return std::to_string(bytes / mb) + "M";
    return std::to_string(bytes);
}

}  // namespace

std::string render_pool(const Config& cfg, const SiteConfig& site, const std::string& agensio_group) {
    const PhpPool& p = site.pool;
    std::ostringstream o;
    o << kHeader << " from " << cfg.config_path.string() << " for user " << site.user
      << "; do not edit, rerun `agensio pools`\n";
    o << "[" << p.name << "]\n";
    o << "user = " << site.user << "\n";
    o << "group = " << (site.group.empty() ? site.user : site.group) << "\n";
    o << "listen = " << p.socket << "\n";
    o << "listen.owner = " << site.user << "\n";
    o << "listen.group = " << agensio_group << "\n";
    o << "listen.mode = 0660\n";
    o << "pm = " << p.pm << "\n";
    o << "pm.max_children = " << p.children << "\n";
    if (p.pm == "dynamic") {
        // Half the children on standby, one idle at least: php-fpm insists on these keys.
        const unsigned start = std::max(1u, p.children / 2);
        o << "pm.start_servers = " << start << "\npm.min_spare_servers = 1\npm.max_spare_servers = " << start
          << "\n";
    }
    if (p.max_requests) o << "pm.max_requests = " << p.max_requests << "\n";
    o << "catch_workers_output = yes\n";
    o << "clear_env = yes\n";
    o << "env[PATH] = /usr/local/bin:/usr/bin:/bin\n";
    o << "php_admin_value[open_basedir] = " << join(p.open_basedir, ':') << "\n";
    o << "php_admin_value[upload_tmp_dir] = " << p.state_dir << "/tmp\n";
    o << "php_admin_value[sys_temp_dir] = " << p.state_dir << "/tmp\n";
    o << "php_admin_value[session.save_path] = " << p.state_dir << "/sessions\n";
    o << "php_admin_value[memory_limit] = " << p.memory_limit << "\n";
    o << "php_admin_value[max_execution_time] = " << p.max_execution_time << "\n";
    o << "php_admin_value[upload_max_filesize] = " << ini_size(cfg.max_body_size) << "\n";
    o << "php_admin_value[post_max_size] = " << ini_size(cfg.max_body_size) << "\n";
    o << "php_admin_flag[expose_php] = off\n";
    for (const auto& [k, v] : p.extra) o << "php_admin_value[" << k << "] = " << v << "\n";
    return o.str();
}

std::vector<GeneratedPool> generated_pools(const Config& cfg, const std::string& agensio_group) {
    std::vector<GeneratedPool> out;
    for (const auto& site : cfg.sites) {
        if (!site.pool.generated) continue;
        bool seen = false;
        for (const auto& g : out) seen = seen || g.user == site.user;
        if (seen) continue;  // the sites of a user agree (checked at load); the first renders
        out.push_back({site.pool.name, site.user, site.group.empty() ? site.user : site.group, site.pool.state_dir,
                       render_pool(cfg, site, agensio_group)});
    }
    return out;
}

std::string current_group_name() {
#ifndef _WIN32
    if (const struct group* g = ::getgrgid(::getegid())) return g->gr_name;
#endif
    return {};
}

fs::path pools_dir(const Config& cfg, const std::string& version) {
    if (!cfg.pools_dir.empty()) return cfg.pools_dir;
    // Debian/Ubuntu: /etc/php/<version>/fpm/pool.d; brew: <prefix>/etc/php/<version>/php-fpm.d;
    // RHEL/Fedora: /etc/php-fpm.d; Alpine: /etc/php<NN>/php-fpm.d. Newest version wins.
    std::error_code ec;
    for (const char* prefix : {"/etc/php", "/opt/homebrew/etc/php", "/usr/local/etc/php"}) {
        const fs::path base(prefix);
        if (!fs::is_directory(base, ec)) continue;
        fs::path best;
        for (const auto& entry : fs::directory_iterator(base, ec)) {
            const std::string v = entry.path().filename().string();
            if (!version.empty() && v != version) continue;
            if (!fs::is_directory(entry.path() / "fpm" / "pool.d", ec) &&
                !fs::is_directory(entry.path() / "php-fpm.d", ec))
                continue;
            if (best.empty() || v > best.filename().string()) best = entry.path();
        }
        if (best.empty()) continue;
        return fs::is_directory(best / "fpm" / "pool.d", ec) ? best / "fpm" / "pool.d" : best / "php-fpm.d";
    }
    if (fs::is_directory("/etc/php-fpm.d", ec)) return "/etc/php-fpm.d";
    for (const auto& entry : fs::directory_iterator("/etc", ec)) {
        const std::string n = entry.path().filename().string();
        if (n.starts_with("php") && fs::is_directory(entry.path() / "php-fpm.d", ec)) return entry.path() / "php-fpm.d";
    }
    return {};
}

int write_pools(const Config& cfg, const fs::path& out_dir, bool dry_run, std::ostream& out) {
#ifdef _WIN32
    (void)cfg;
    (void)out_dir;
    (void)dry_run;
    out << "error: generated php-fpm pools are not supported on Windows\n";
    return 1;
#else
    std::string agensio_group = cfg.group.empty() ? current_group_name() : cfg.group;
    if (agensio_group.empty()) {
        out << "error: cannot determine agensio's group; set server.group\n";
        return 1;
    }
    std::error_code ec;
    if (!fs::is_directory(out_dir, ec)) {
        out << "error: pool directory " << out_dir.string() << " does not exist\n";
        return 1;
    }
    const auto pools = generated_pools(cfg, agensio_group);
    bool changed = false;
    const char* verb = dry_run ? "would write" : "wrote";

    for (const auto& p : pools) {
        // State directories: 0700 and owned by the user; chown needs root, so without it
        // the directories stay ours and one warning per user says what to fix.
        const struct passwd* pw = ::getpwnam(p.user.c_str());
        const struct group* gr = ::getgrnam(p.group.c_str());
        bool own_warned = false;
        for (const char* sub : {"", "/tmp", "/sessions"}) {
            const fs::path d = p.state_dir + sub;
            if (fs::is_directory(d, ec)) continue;
            if (dry_run) {
                out << "would create " << d.string() << "\n";
                continue;
            }
            if (!fs::create_directories(d, ec) && ec) {
                out << "error: cannot create " << d.string() << ": " << ec.message() << "\n";
                return 1;
            }
            ::chmod(d.c_str(), 0700);
            const bool owned = pw && gr && ::chown(d.c_str(), pw->pw_uid, gr->gr_gid) == 0;
            if (!owned && !own_warned) {
                own_warned = true;
                if (!pw || !gr) out << "warning: user " << p.user << " or group " << p.group << " does not exist; ";
                else out << "warning: not root, cannot chown; ";
                out << p.state_dir << " stays owned by us and PHP cannot write there until it is "
                    << p.user << ":" << p.group << "\n";
            }
            out << "created " << d.string() << "\n";
        }
        const fs::path file = out_dir / (p.name + ".conf");
        std::string current;
        if (std::ifstream in(file); in) current.assign(std::istreambuf_iterator<char>(in), {});
        if (current == p.text) continue;
        if (!current.empty() && !current.starts_with(kHeader)) {
            out << "error: " << file.string() << " exists and was not generated by agensio; remove it or rename the user\n";
            return 1;
        }
        changed = true;
        out << verb << " " << file.string() << "\n";
        if (dry_run) continue;
        const fs::path tmp = file.string() + ".tmp";
        {
            std::ofstream f(tmp, std::ios::trunc);
            f << p.text;
            if (!f) {
                out << "error: cannot write " << tmp.string() << "\n";
                return 1;
            }
        }
        ::chmod(tmp.c_str(), 0644);
        fs::rename(tmp, file, ec);
        if (ec) {
            out << "error: cannot replace " << file.string() << ": " << ec.message() << "\n";
            return 1;
        }
    }

    // Files we generated for users that are no longer configured.
    for (const auto& entry : fs::directory_iterator(out_dir, ec)) {
        const std::string name = entry.path().filename().string();
        if (!name.starts_with("agensio-") || !name.ends_with(".conf")) continue;
        bool wanted = false;
        for (const auto& p : pools) wanted = wanted || name == p.name + ".conf";
        if (wanted) continue;
        std::string first;
        std::ifstream in(entry.path());
        std::getline(in, first);
        if (!first.starts_with(kHeader)) continue;
        changed = true;
        out << (dry_run ? "would remove " : "removed ") << entry.path().string() << "\n";
        if (!dry_run) fs::remove(entry.path(), ec);
    }
    if (!changed) out << "pools up to date (" << pools.size() << ")\n";
    else if (!dry_run) out << "reload php-fpm to apply\n";
    return changed ? 3 : 0;
#endif
}

}  // namespace agensio
