// Generated by tools/gen-hpack-tables.py from RFC 7541 appendix C. Do not edit.
#pragma once

#include <string_view>
#include <vector>

namespace agensio::hpack_vectors {

struct Field {
    std::string_view name;
    std::string_view value;
};
struct Vector {
    std::string_view name;
    int group;               // examples of one group share a connection (dynamic table)
    std::string_view hex;    // the encoded block
    std::vector<Field> fields;
    unsigned table_size_after;
    unsigned max_table;
};

inline const std::vector<Vector>& all() {
    static const std::vector<Vector> v = {
        {"C.2.1 Literal Header Field with Indexing", 2, "400a637573746f6d2d6b65790d637573746f6d2d686561646572", {{"custom-key", "custom-header"}}, 55, 4096},
        {"C.2.2 Literal Header Field without Indexing", 2, "040c2f73616d706c652f70617468", {{":path", "/sample/path"}}, 0, 4096},
        {"C.2.3 Literal Header Field Never Indexed", 2, "100870617373776f726406736563726574", {{"password", "secret"}}, 0, 4096},
        {"C.2.4 Indexed Header Field", 2, "82", {{":method", "GET"}}, 0, 4096},
        {"C.3.1 First Request", 3, "828684410f7777772e6578616d706c652e636f6d", {{":method", "GET"}, {":scheme", "http"}, {":path", "/"}, {":authority", "www.example.com"}}, 57, 4096},
        {"C.3.2 Second Request", 3, "828684be58086e6f2d6361636865", {{":method", "GET"}, {":scheme", "http"}, {":path", "/"}, {":authority", "www.example.com"}, {"cache-control", "no-cache"}}, 110, 4096},
        {"C.3.3 Third Request", 3, "828785bf400a637573746f6d2d6b65790c637573746f6d2d76616c7565", {{":method", "GET"}, {":scheme", "https"}, {":path", "/index.html"}, {":authority", "www.example.com"}, {"custom-key", "custom-value"}}, 164, 4096},
        {"C.4.1 First Request", 4, "828684418cf1e3c2e5f23a6ba0ab90f4ff", {{":method", "GET"}, {":scheme", "http"}, {":path", "/"}, {":authority", "www.example.com"}}, 57, 4096},
        {"C.4.2 Second Request", 4, "828684be5886a8eb10649cbf", {{":method", "GET"}, {":scheme", "http"}, {":path", "/"}, {":authority", "www.example.com"}, {"cache-control", "no-cache"}}, 110, 4096},
        {"C.4.3 Third Request", 4, "828785bf408825a849e95ba97d7f8925a849e95bb8e8b4bf", {{":method", "GET"}, {":scheme", "https"}, {":path", "/index.html"}, {":authority", "www.example.com"}, {"custom-key", "custom-value"}}, 164, 4096},
        {"C.5.1 First Response", 5, "4803333032580770726976617465611d4d6f6e2c203231204f637420323031332032303a31333a323120474d546e1768747470733a2f2f7777772e6578616d706c652e636f6d", {{":status", "302"}, {"cache-control", "private"}, {"date", "Mon, 21 Oct 2013 20:13:21 GMT"}, {"location", "https://www.example.com"}}, 222, 256},
        {"C.5.2 Second Response", 5, "4803333037c1c0bf", {{":status", "307"}, {"cache-control", "private"}, {"date", "Mon, 21 Oct 2013 20:13:21 GMT"}, {"location", "https://www.example.com"}}, 222, 256},
        {"C.5.3 Third Response", 5, "88c1611d4d6f6e2c203231204f637420323031332032303a31333a323220474d54c05a04677a69707738666f6f3d4153444a4b48514b425a584f5157454f50495541585157454f49553b206d61782d6167653d333630303b2076657273696f6e3d31", {{":status", "200"}, {"cache-control", "private"}, {"date", "Mon, 21 Oct 2013 20:13:22 GMT"}, {"location", "https://www.example.com"}, {"content-encoding", "gzip"}, {"set-cookie", "foo=ASDJKHQKBZXOQWEOPIUAXQWEOIU; max-age=3600; version=1"}}, 215, 256},
        {"C.6.1 First Response", 6, "488264025885aec3771a4b6196d07abe941054d444a8200595040b8166e082a62d1bff6e919d29ad171863c78f0b97c8e9ae82ae43d3", {{":status", "302"}, {"cache-control", "private"}, {"date", "Mon, 21 Oct 2013 20:13:21 GMT"}, {"location", "https://www.example.com"}}, 222, 256},
        {"C.6.2 Second Response", 6, "4883640effc1c0bf", {{":status", "307"}, {"cache-control", "private"}, {"date", "Mon, 21 Oct 2013 20:13:21 GMT"}, {"location", "https://www.example.com"}}, 222, 256},
        {"C.6.3 Third Response", 6, "88c16196d07abe941054d444a8200595040b8166e084a62d1bffc05a839bd9ab77ad94e7821dd7f2e6c7b335dfdfcd5b3960d5af27087f3672c1ab270fb5291f9587316065c003ed4ee5b1063d5007", {{":status", "200"}, {"cache-control", "private"}, {"date", "Mon, 21 Oct 2013 20:13:22 GMT"}, {"location", "https://www.example.com"}, {"content-encoding", "gzip"}, {"set-cookie", "foo=ASDJKHQKBZXOQWEOPIUAXQWEOIU; max-age=3600; version=1"}}, 215, 256},
    };
    return v;
}

}  // namespace agensio::hpack_vectors
